# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('value', models.IntegerField()),
                ('author', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('date', models.IntegerField()),
                ('time', models.CharField(max_length=20)),
                ('sphere', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('dop', models.CharField(max_length=200)),
                ('cycle', models.CharField(max_length=200)),
                ('finished', models.CharField(max_length=200)),
                ('edited', models.CharField(max_length=200)),
                ('fin_ver', models.CharField(max_length=200)),
                ('orpho', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=200)),
            ],
        ),
    ]
